# Generated by Django 3.2.16 on 2026-09-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_alter_wrapper_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrapper',
            options={'verbose_name': 'объект «Обёртка»', 'verbose_name_plural': 'Обёртки'},
        ),
    ]
