# Generated by Django 5.2.17 on 2026-09-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0008_icecream_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
